# Generated by Django 6.0.2 on 2026-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FML_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
