# Generated by Django 6.0.2 on 2026-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FML_app', '0006_message_newsletter_comment_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
