# Generated by Django 6.0.2 on 2026-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FML_app', '0007_message_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
