# Generated by Django 6.0.2 on 2026-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FML_app', '0008_comment_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
