# Generated by Django 6.0.2 on 2026-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FML_app', '0009_post_quote_post_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
